#!/bin/bash
# Railway Database Setup - Manual Steps
# Railway CLI is having issues with interactive prompts
# Follow these steps in Railway Dashboard instead

echo "🚀 Railway Manual Setup Guide"
echo "=============================="
echo ""
echo "✅ Project Created: divadaulti-production"
echo "🔗 Dashboard: https://railway.com/project/d47fa477-a934-4662-a039-f5007b32e0fc"
echo ""
echo "Follow these steps in Railway Dashboard:"
echo ""
echo "STEP 1: Add PostgreSQL Database"
echo "  1. Open: https://railway.com/project/d47fa477-a934-4662-a039-f5007b32e0fc"
echo "  2. Click '+ New' button"
echo "  3. Select 'Database'"
echo "  4. Click 'Add PostgreSQL'"
echo "  5. Wait 30 seconds for provisioning"
echo ""
echo "STEP 2: Get Database Credentials"
echo "  1. Click on the PostgreSQL service"
echo "  2. Go to 'Variables' tab"
echo "  3. Find 'DATABASE_URL'"
echo "  4. Click 'Copy' button"
echo ""
echo "STEP 3: Create Database Schema"
echo "  Run this command (paste DATABASE_URL when prompted):"
echo "  ./setup_railway_db.sh"
echo ""
echo "STEP 4: Import Data"
echo "  ./import_data_railway.sh"
echo ""
echo "STEP 5: Add Next.js Service"
echo "  1. In Railway dashboard, click '+ New'"
echo "  2. Select 'GitHub Repo'"
echo "  3. Connect your repository"
echo "  4. Railway auto-detects Next.js"
echo ""
echo "STEP 6: Set Environment Variables"
echo "  1. Click on Next.js service"
echo "  2. Go to 'Variables' tab"
echo "  3. Add these variables:"
echo "     - DATABASE_URL: \${{Postgres.DATABASE_URL}}"
echo "     - NODE_ENV: production"
echo "     - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: (from cloudinary.com)"
echo "     - CLOUDINARY_API_KEY: (from cloudinary.com)"
echo "     - CLOUDINARY_API_SECRET: (from cloudinary.com)"
echo ""
echo "STEP 7: Deploy"
echo "  Railway will auto-deploy when you connect GitHub repo"
echo ""
read -p "Press Enter when PostgreSQL is added and you have DATABASE_URL..."
